export const strings = {
  brand: {
    name: "Advaita Hygiene Solutions",
    subtitleLine1: "Wholesaler & Distributor of",
    subtitleLine2: "Washroom • Cleaning • Waste Management Solutions",
    logoAlt: "Advaita Hygiene logo",
  },
  nav: {
    products: "Products",
    aboutUs: "About Us",
    why: "Why AHS",
    process: "Process",
    catalog: "Catalog",
    catalogue: "Catalogue",
    quote: "Get Wholesale Quote",
  },
  header: {
    location: "Bengaluru, India",
    phone: "9036056006",
    responseTime: "95%",
    responseTimeLabel: "Response time",
    searchPlaceholder: "Search products…",
    searchAria: "Search products",
    menuAria: "Open menu",
    closeMenuAria: "Close menu",
    noResults: "No products found",
  },
  hero: {
    eyebrow: "AHS – Advaita Hygiene Solutions",
    primaryCta: "Get Wholesale Quote",
    secondaryCta: "Browse Products",
    ariaPrev: "Previous slide",
    ariaNext: "Next slide",
    ariaGoTo: (index: number) => `Go to slide ${index}`,
  },
  solutions: {
    eyebrow: "Our Products",
    title: "Core Product Categories We Supply",
    body:
      "Wholesale distributors of Washroom, Cleaning, and Waste Management solutions. Serving Retailers, Distributors, Corporate Offices, and Institutions.",
  },
  why: {
    eyebrow: "Why Choose AHS",
    title: "Why 500+ Buyers Choose AHS",
  },
  industries: {
    eyebrow: "Sectors We Serve",
    title: "Trusted Across Every Sector",
    body: "Wholesale distributors of Washroom, Cleaning, and Waste Management solutions. Serving Retailers, Distributors, Corporate Offices, and Institutions.",
  },
  process: {
    eyebrow: "Procurement Process",
    title: "Simple Process. Reliable Supply.",
  },
  closing: {
    title: "Ready to stock with confidence?",
    subtitle: "Wholesale distributors of Washroom, Cleaning, and Waste Management solutions. Serving Retailers, Distributors, Corporate Offices, and Institutions. Get a quote in 2 hours.",
    primaryCta: "Request Wholesale Quote",
    whatsappCta: "💬 Chat on WhatsApp",
  },
  trust: {
    label: "Trust Indicators",
  },
  productCard: {
    priceSuffix: "/ piece",
    detailsCta: "Call now",
  callNumber: "9036056006",
    quoteCta: "Get quote",
    sizesPrefix: "Sizes:",
    sizePrefix: "Size:",
    seeAllTitle: "See All Products",
    seeAllSubtitle: "Explore the full catalogue",
    moreCta: "More >>",
  },
  modals: {
    quoteTitle: "Get Wholesale Quote",
    callbackTitle: "Request Callback",
  },
  forms: {
    quoteSuccess:
      "Quote request submitted successfully! We'll get back to you soon.",
    callbackSuccess:
      "Callback request received! Our team will contact you within 24 hours.",
    quote: {
      name: "Name *",
      phone: "Phone Number *",
      message: "Additional requirement (Optional)",
      cancel: "Cancel",
      submit: "Get Quote",
      ok: "OK",
      successTitle: "Quote request received",
    },
    callback: {
      name: "Name *",
      phone: "Phone Number *",
      time: "Preferred Time",
      message: "Brief Requirement",
      cancel: "Cancel",
      submit: "Request Callback",
      options: {
        morning: "Morning (9 AM - 12 PM)",
        afternoon: "Afternoon (12 PM - 4 PM)",
        evening: "Evening (4 PM - 7 PM)",
      },
    },
  },
  comingSoon: {
    headline: "Coming Soon",
    subline: "We're building a simpler way to source washroom, cleaning, and waste management supplies—all from one trusted partner.",
    /** ISO date string for countdown; e.g. "2025-06-01T00:00:00" */
    launchDate: "2025-06-01T00:00:00",
    countdownLabel: "Launching in",
    cta: "Get notified when we launch",
    backToHome: "Back to home",
    problemsTitle: "What we solve",
    problems: [
      {
        title: "Fragmented supply",
        body: "No more juggling multiple vendors for washroom, cleaning, and waste. One order, one relationship, one invoice.",
      },
      {
        title: "Quality & consistency",
        body: "Reliable brands and consistent stock so your facilities meet hygiene and safety standards without guesswork.",
      },
      {
        title: "Lead times & logistics",
        body: "Predictable delivery and clear minimums. Spend less time chasing orders and more time running your business.",
      },
      {
        title: "Compliance made simple",
        body: "Products that meet institutional and corporate requirements. We help you stay compliant without the hassle.",
      },
    ],
  },
  productDetail: {
    back: "← Back to Catalogue",
    allProductsTitle: "Products by category",
    menuExpand: "Expand category",
    menuCollapse: "Collapse category",
    quoteCta: "Get Wholesale Quote",
    callbackCta: "Request Callback",
    pricePill: "Get Latest Price",
    minOrderLabel: "Minimum order quantity:",
    minOrderUnit: "Piece",
    descriptionTitle: "Product Description",
    featuresTitle: "Features",
    interestedCta: "Yes! I am interested",
    browseMore: "Browse More Products",
    specLabels: {
      capacity: "Capacity",
      material: "Material",
      color: "Color",
      structure: "Structure",
      usage: "Usage",
      size: "Size",
      grade: "Grade",
      finish: "Finish",
    },
  },
};
